title: ONE PIECE
author: FleurBlanche
email: 1007759354@qq.com
description: > # this means to ignore newlines until "show_exerpts:"
  My test blog site.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: My Blog Test Page
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

  navigation:
    - title: HOME
      url: "/#"

  # generate social links in footer
  social_links:
    # twitter: dream_dramea
    github:  FleurBlanche
    # linkedIn: in/thelehhman
    # rss: rss
 
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed

remote_theme: thelehhman/texture